# Generated by Django 5.0.6 on 2024-06-30 03:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braille_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brailleinfo',
            name='date_saved',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
