# Generated by Django 5.0.6 on 2024-06-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braille_app', '0002_brailleinfo_date_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='brailleinfo',
            name='filename',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
