# Generated by Django 5.0 on 2024-09-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braille_app', '0004_activityhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='brailleinfo',
            name='deleteflag',
            field=models.BooleanField(default=False),
        ),
    ]
