# Generated by Django 5.0 on 2024-09-11 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braille_app', '0005_brailleinfo_deleteflag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedBraille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('braille_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='braille_app.brailleinfo')),
                ('shared_to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brailler_receiver', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='braille_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SharedBraille',
            },
        ),
    ]
