# Generated by Django 5.0 on 2024-09-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braille_app', '0006_sharedbraille'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_faculty', models.BooleanField(default=False, verbose_name='is_faculty')),
                ('is_student', models.BooleanField(default=False, verbose_name='is_student')),
                ('deleteflag', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'UserProfile',
            },
        ),
    ]
