# Generated by Django 5.0 on 2024-09-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braille_app', '0008_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityhistory',
            name='date_log',
            field=models.DateField(auto_now_add=True),
        ),
    ]
