# Generated by Django 5.0 on 2024-09-14 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braille_app', '0010_userprofile_initial_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedbraille',
            name='date_shared',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 9, 14, 10, 21, 11, 575867, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
