# Generated by Django 5.0 on 2024-12-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braille_app', '0011_sharedbraille_date_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='school_year',
            field=models.CharField(default='2024', max_length=4, verbose_name='school_year'),
        ),
    ]
