# Generated by Django 5.0 on 2024-12-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braille_app', '0013_userprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedbraille',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
